actuators:
  raw_data:
    position_port: act_position
    effort_port: act_current
    mode_port: act_control_mode
    position_cmd_port: ref_position
    effort_cmd_port: ref_current
    mode_cmd_port: ref_control_mode
    torque_sensor_port: act_torque

e_stop:
  raw_data:
    e_stop_port: emergency_stop_state

force_torque:
  left_ft:
    frame: leg_left_6_link
    raw_data:
      force_port: force_ankle_left
      torque_port: torque_ankle_left
  right_ft:
    frame: leg_right_6_link
    raw_data:
      force_port: force_ankle_right
      torque_port: torque_ankle_right

#imu:
#  base_imu:
#    frame: base_link
#    raw_data:
#      orientation_port: orientation_base

#ros_control_component:
#  ignore_read_errors: true

