leg_right_4_joint_force_control:
  type: "ModuleTestbenchTorqueControl"

  dt: 0.001

  joints:
    - leg_left_6_joint
    
  gains:
    leg_left_6_joint: {p: 0.0, d: 0.0, i:  0.0, i_clamp: 0.0, torque_clamp: 0.0}

leg_right_6_joint_force_control:
  type: "ModuleTestbenchTorqueControl"

  dt: 0.001

  joints:
    - leg_left_6_joint
    
  gains:
    leg_left_6_joint: {p: 0.0, d: 0.0, i:  0.0, i_clamp: 0.0, torque_clamp: 0.0}
    
leg_right_5_joint_force_control:
  type: "ModuleTestbenchTorqueControl"

  dt: 0.001

  joints:
    - leg_left_5_joint
    
  gains:
    leg_left_5_joint: {p: 0.0, d: 0.0, i:  0.0, i_clamp: 0.0, torque_clamp: 0.0}
