actuators:
  raw_data:
    position_port: act_position
    velocity_port: act_velocity
    effort_port: act_current
    mode_port: act_control_mode
    position_cmd_port: ref_position
    effort_cmd_port: ref_current
    mode_cmd_port: ref_control_mode
    absolute_encoder_position_port: act_abs_position
    torque_sensor_port: act_torque
    temperature_sensor_port: act_temperature


e_stop:
  raw_data:
    e_stop_port: emergency_stop_state

force_torque:
  left_ankle_ft:
    frame: leg_left_6_link
    transformation:
      force: [x,-y,-z]
      torque: [x,-y,-z]
    raw_data:
      force_port: force_ankle_left
      torque_port: torque_ankle_left
  right_ankle_ft:
    frame: leg_right_6_link
    transformation:
      force: [x,-y,-z]
      torque: [x,-y,-z]
    raw_data:
      force_port: force_ankle_right
      torque_port: torque_ankle_right

imu:
  base_imu:
    frame: imu_link
    raw_data:
      orientation_port: orientation_base
      linear_acceleration_port: linear_acceleration_base
      angular_velocity_port: angular_velocity_base
    transformation:
      # [pi, 0, pi/2] (NED -> ENU)
      orientation_to_enu_frame: [3.14159265358979, 0, 1.57079632679490]

#ros_control_component:
#  ignore_read_errors: true

