left_leg_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - leg_left_1_joint
    - leg_left_2_joint
    - leg_left_3_joint
    - leg_left_4_joint
    - leg_left_5_joint
    - leg_left_6_joint
  constraints:
    goal_time: &goal_time_constraint 0.6
    stopped_velocity_tolerance: *stopped_velocity_constraint
    arm_left_1_joint:
      goal: &goal_pos_constraint 0.02
    arm_left_2_joint:
      goal: *goal_pos_constraint
    arm_left_3_joint:
      goal: *goal_pos_constraint
    arm_left_4_joint:
      goal: *goal_pos_constraint
    arm_left_5_joint:
      goal: *goal_pos_constraint
    arm_left_6_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0

right_leg_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - leg_right_1_joint
    - leg_right_2_joint
    - leg_right_3_joint
    - leg_right_4_joint
    - leg_right_5_joint
    - leg_right_6_joint
  constraints:
    goal_time: *goal_time_constraint
    stopped_velocity_tolerance: *stopped_velocity_constraint
    arm_right_1_joint:
      goal: *goal_pos_constraint
    arm_right_2_joint:
      goal: *goal_pos_constraint
    arm_right_3_joint:
      goal: *goal_pos_constraint
    arm_right_4_joint:
      goal: *goal_pos_constraint
    arm_right_5_joint:
      goal: *goal_pos_constraint
    arm_right_6_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0
